# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libnetwork_sources = [
    'EpollEvent.cpp',
    'Transport.cpp',
    'ServerAdapter.cpp',
    'TcpAcceptor.cpp',
    'IOComponent.cpp',
    'Socket.cpp',
    'ServerSocket.cpp',
    'ClientSocket.cpp',
    'IOEvent.cpp',
    'PacketStream.cpp',
    'Packet.cpp',
    'TcpConnection.cpp',
    'DefaultPacket.cpp',
    'IPacketHandler.cpp',
    'SessionPool.cpp',
    'Session.cpp',
    'DefaultPacketStream.cpp',
    'TimeoutPacket.cpp',
    ]

env.SharedLibrary(target = 'tnet_network',
                  source = libnetwork_sources,
                  CPPPATH = env['install_root'])

SConscript('test/SConscript', 'env')
