# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libnetwork_sources = [
    'EpollEvent.cpp',
    'Transport.cpp',
    'ServerAdapter.cpp',
    'ClientAdapter.cpp',
    'TcpAcceptor.cpp',
    'IOComponent.cpp',
    'Socket.cpp',
    'ServerSocket.cpp',
    'ClientSocket.cpp',
    'IOEvent.cpp',
    ]

env.SharedLibrary(target = 'tnet_network',
              source = libnetwork_sources)

SConscript('test/SConscript', 'env')
