# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    ]

env.SharedLibrary(target = 'tnet_common',
                  source = libcommon_sources,
                  CPPPATH = env['install_root'])

SConscript('test/SConscript', 'env')
