# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libcommon_sources = [
    'Packet.cpp',
    ]

env.SharedLibrary(target = 'tnet_common',
              source = libcommon_sources)

SConscript('test/SConscript', 'env')
