# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libutil_sources = [
    'StringUtil.cpp',
    'Thread.cpp',
    ]

env.SharedLibrary(target = 'tnet_util',
              source = libutil_sources)

SConscript('test/SConscript', 'env')
