# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

libutil_sources = [
    'StringUtil.cpp',
    'Thread.cpp',
    'MemPool.cpp',
    'TimeUtility.cpp',
    ]

env.SharedLibrary(target = 'tnet_util',
                  source = libutil_sources,
                  CPPPATH = env['install_root'])

SConscript('test/SConscript', 'env')
