// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rpc_extensions.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "rpc_extensions.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tnet {

namespace {


}  // namespace


void protobuf_AssignDesc_rpc_5fextensions_2eproto() {
  protobuf_AddDesc_rpc_5fextensions_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "rpc_extensions.proto");
  GOOGLE_CHECK(file != NULL);
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_rpc_5fextensions_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
}

}  // namespace

void protobuf_ShutdownFile_rpc_5fextensions_2eproto() {
}

void protobuf_AddDesc_rpc_5fextensions_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::protobuf_AddDesc_google_2fprotobuf_2fdescriptor_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\024rpc_extensions.proto\022\004tnet\032 google/pro"
    "tobuf/descriptor.proto:4\n\nservice_id\022\037.g"
    "oogle.protobuf.ServiceOptions\030\350\007 \002(\r:2\n\t"
    "method_id\022\036.google.protobuf.MethodOption"
    "s\030\350\007 \002(\r", 168);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rpc_extensions.proto", &protobuf_RegisterTypes);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::ServiceOptions::default_instance(),
    1000, 13, false, false);
  ::google::protobuf::internal::ExtensionSet::RegisterExtension(
    &::google::protobuf::MethodOptions::default_instance(),
    1000, 13, false, false);
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_rpc_5fextensions_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_rpc_5fextensions_2eproto {
  StaticDescriptorInitializer_rpc_5fextensions_2eproto() {
    protobuf_AddDesc_rpc_5fextensions_2eproto();
  }
} static_descriptor_initializer_rpc_5fextensions_2eproto_;
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::ServiceOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  service_id(kServiceIdFieldNumber, 0u);
::google::protobuf::internal::ExtensionIdentifier< ::google::protobuf::MethodOptions,
    ::google::protobuf::internal::PrimitiveTypeTraits< ::google::protobuf::uint32 >, 13, false >
  method_id(kMethodIdFieldNumber, 0u);

// @@protoc_insertion_point(namespace_scope)

}  // namespace tnet

// @@protoc_insertion_point(global_scope)
