# -*- mode: python -*-
Import('env')
env.MergeFlags('-I.')

lib_trpc_sources = [
    'rpc_extensions.pb.cc',
    'TnetRPCChannel.cpp',
    'RpcServer.cpp',
    'ChannelManager.cpp',
    'RPCPacketHandler.cpp',
    'RPCReturnArg.cpp',
    'SyncRPCClosure.cpp',
    'TnetRpcController.cpp',
    ]

env.SharedLibrary(target = 'trpc',
                  source = lib_trpc_sources,
                  CPPPATH = env['install_root'])

#SConscript('test/SConscript', 'env')
