# -*- mode: python -*-
import os
Import('env')

libnetwork_sources = [
    'mainTest.cpp',
    'TransportTest.cpp',
    'SessionPoolTest.cpp',
    'DefaultPacketStreamTest.cpp',
    ]

env.Program('tnet_network_test',
            libnetwork_sources,
            LIBS = ['glog', 'gtest', 'tnet_network', 'tnet_util', 'pthread'], 
            LIBPATH = ['.', '../', '../../util', '../../../lib/'])

utiltest = env.uTest('unittest', 'tnet_network_test')

