# -*- mode: python -*-
import os
Import('env')

libutil_sources = [
    'StringUtilTest.cpp',
    'mainTest.cpp',
    'ThreadTest.cpp',
    'LockTest.cpp',
    ]

env.Program('tnet_util_test',
            libutil_sources,
            LIBS = ['glog', 'gtest', 'tnet_util', 'pthread'], 
            LIBPATH = ['.', '../', '../../../lib/'])

utiltest = env.uTest('unittest', 'tnet_util_test')

